spring:
  datasource:
    url: jdbc:postgresql://${MY_POSTGRES_HOST:localhost}:15432/docker_security_jwt
    driver-class-name: org.postgresql.Driver
    username: ${USERNAME_POSTGRES:postgres}
    password: ${PASSWORD_POSTGRES:785785}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
#    user: ${USERNAME_POSTGRES:postgres}
#    password: ${PASSWORD_POSTGRES:785785}
    baseline-description: "init"
    baseline-version: 0
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  server:
    base:
      path: ${MY_VARIABLE:172.121.0.1}
      port: 8080
jwt:
  secret: 20f31fbce8c54800bffa5f5d767f2cf142ebcfb87ac4ab76c0c55ba7f1934481
  lifetime: 30m
